#PBS -N BBDukTrim
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=28
#PBS -j oe
cd $PBS_O_WORKDIR
cp -r woo0024/project1/ woo0024/software/ /users/PWOO0003/woo0024/ $TMPDIR
cd $TMPDIR
bbmap/bbduk.sh -Xmx20g in = woo0024/project1/inFile1.fastq, woo0024/project1/inFile2.fastq, woo0024/project1/inFile3.fastq out=output1.fqoutput2.fqoutput3.fq
ref=adapters.fa ktrim=r tpe tbo qtrim=rl trimq=13 maq=12 
cp -r $TMPDIR $PBS_O_WORKDIR
